---
openapi: 3.0.1
info:
  title: Test API
  description: An ASP.NET Core Web API used to demonstrate one way to document APIs
  termsOfService: https://example.com/terms
  contact:
    name: Example Contact
    url: https://example.com/contact
  license:
    name: Example License
    url: https://example.com/license
  version: v1
paths:
  "/WeatherForecast":
    get:
      tags:
      - WeatherForecast
      summary: Retrieve an array of the next 5 days forecasts
      description: "Sample request:\r\n    GET\r\n    {}"
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/WeatherForecast"
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/WeatherForecast"
            text/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/WeatherForecast"
        '201':
          description: Returns the newly created item
        '400':
          description: If the item is null
components:
  schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperatureC:
          type: integer
          format: int32
        summary:
          type: string
          nullable: true
        temperatureF:
          type: integer
          format: int32
          readOnly: true
      additionalProperties: false
